import { StyleSheet, Dimensions } from 'react-native';

export default StyleSheet.create({
  container: {
  	flex: 1,
    backgroundColor: '#FDE1DC',
    alignItems: 'center',
    flexDirection: 'column',
  },
  cover: {
  	flex: 1,
  	marginTop: 20,
    height: 200,
    width: 200,
    resizeMode: 'contain',
    alignItems: 'flex-start',
  },
  input: {
    margin: 8,
    borderWidth: 3,
    width: 250,
    borderBottomColor: '#707070',
    borderTopColor: '#FDE1DC',
    borderLeftColor: '#FDE1DC',
    borderRightColor: '#FDE1DC',
    flexDirection: 'row',
  },
  inputText: {
    fontSize: 18,
    textAlign: 'left',
    color: '#707070',
    padding: 8,
  },
  inputIcon: {
  	height: 26,
  	width: 26,
  },
  button: {
  	backgroundColor: '#ABF5D2',
  	margin: 60,
  	width: 250,
  	height: 50,
  	alignItems: 'center',
  	borderRadius: 25,
  	justifyContent: 'center',
  },
  buttonPressed: {
  	backgroundColor: '#ABFFFF',
  	color: '#ABF5D2',
  	marginTop: 60,
  	width: 250,
  	height: 50,
  	alignItems: 'center',
  	borderRadius: 25,
  },
  buttonText: {
  	fontSize: 18,
  	textAlign: 'center',
  	margin: 8,
  	color: '#707070',
  },
  itemBoard: {
  	zIndex: 0,
  	backgroundColor: '#FFF7E0',
  	marginTop: 20,
  	width: 290,
  	height: 260,
  	alignItems: 'center',
  	borderRadius: 25,
  	margin: 28,
  },
  itemText: {
  	color: "#707070",
  	fontSize: 50,
  	textAlign: 'center',
  },
  swipeLink: {
  	margin: 20,
  	backgroundColor: '#D5D5D5',
  	height: 10,
  	width: 60,
  	borderRadius: 25,
    alignSelf: 'center',
  },
  doubleSeparator: {
  	backgroundColor: '#D5D5D5',
  	height: 10,
  	width: 280,
  	borderWidth: 3,
  	borderRadius: 25,
  	borderBottomColor: '#000000',
    borderTopColor: '#000000',
    borderLeftColor: '#FFF7E0',
    borderRightColor: '#FFF7E0',
  },
  typeText: {
  	color: 'red',
  	fontSize: 20,
  	margin: 8,
  },
  icon: {
  	height: 120,
  	width: 120,
  	resizeMode: 'contain',
  	margin: 8,
  },
  shadow: {
  	shadowColor: '#000',
  	shadowOffset: { width: 5, height: 10 },
  	shadowOpacity: 1,
  	shadowRadius: 8,
  	elevation: 5,
  },
  drawerList: {
  	zIndex: 1,
  	height: Math.round(Dimensions.get('window').height),
  	width: Math.round(Dimensions.get('window').width),
  	alignSelf: 'stretch',
  	backgroundColor: "#FFFFFF",
  	borderRadius: 35,
  	position: 'absolute',
  	top: 350,
  },
  tabIcon: {
  	height: 20,
  	width: 20,
  	resizeMode: 'contain',
  },
  headerBar: {
  	height: 60,
  	width: Math.round(Dimensions.get('window').width),
  	backgroundColor: "#FFFFFF",
  	alignItems: 'center',
  	justifyContent: 'center',
  	flexDirection: 'row',
  },
  headerIcon: {
  	margin: 10,
  	height: 40,
  	width: 40,
  	resizeMode: 'contain',
    zIndex: 1,
    position: 'absolute',
    left: 0,
  },
  headerTitle: {
  	fontSize: 18,
    color: '#707070',
    textAlign: 'center',
    zIndex: 0,
  },
  itemCard: {
  	backgroundColor: '#FFFFFF',
  	width: 290,
  	alignItems: 'center',
  	borderRadius: 25,
  	alignSelf: 'center',
  	marginTop: 10,
  	flex: 1,
  },
  cardImage: {
  	resizeMode: 'stretch',
  	height: 120,
  	width: 290,
  	borderRadius: 25,
  	flexDirection: 'row',
  	alignItems: 'flex-end',
  },
  cardImageText: {
  	fontSize: 18,
    color: '#FFFFFF',
    margin: 15,
    textAlign: 'left',
  },
  cardItemView: {
  	borderRadius: 25,
  	height: 40,
  	width: 250,
  	backgroundColor: '#707070',
  	borderColor: "#000000",
  	borderWidth: 2,
  	margin: 8,
  },
  cardHeaderText:{
  	color: '#707070',
  	margin: 8,
  	fontSize: 18,
  },
  cardItemText: {
  	color: "#FFFFFF",
  	margin: 8,
  },
  flatList: {
  	flex: 1,
  	marginBottom: 150,
  },
  flatListOffers: {
  	flex: 1,
  	height: Math.round(Dimensions.get('window').height),
  	width: Math.round(Dimensions.get('window').width),
  },
  offersCard: {
  	backgroundColor: '#FFFFFF',
  	width: 290,
  	alignItems: 'center',
  	borderRadius: 25,
  	alignSelf: 'center',
  	marginTop: 10,
  	flex: 1,
  },
  offersCardImage: {
  	resizeMode: 'stretch',
  	height: 120,
  	width: 290,
  	borderRadius: 25,
  },
  offersList: {
  	alignItems: 'center',
  	flexDirection: 'column',
  	flex: 1,
  },
  offersItem : {
  	margin: 8,
    width: 250,
    flexDirection: 'row',
  },
  offersItemText: {
  	color: "black",
  	margin: 8,
  	alignSelf: 'center',
  },
});
